### ISSUE TITLE
Help me troubleshoot

### ISSUE THREAD

**Issue by SouravInsights** [githubschool/on-demand-electron-app#2]
### Though I'm on Windows OS, I'm still getting an error while running the build command. I've added a screenshot of my error message down here. @hollenberry  Please help me fix this error.
![capture](https://user-images.githubusercontent.com/26466468/33398312-919bd4ca-d574-11e7-8f85-bf675411530a.JPG)

**Comment by spitford** [comment]
I'm getting the same error on MacOS

**Comment by SouravInsights** [comment]
@spitford Hey, If you are running this in MacOS you can probably solve this issue by following the instructions in this [link](https://services.github.com/on-demand/electron/package-your-app/use-electron-packager/)

**Comment by hollenberry** [comment]
@beardofedu is there any way that you can test this on your Windows partition? I'd be happy to sync with you if so.

**Comment by beardofedu** [comment]
Yea, I can probably test this. Since we are already scheduled to sync tomorrow, lets just add it to the list of things we are reviewing. 👍

**Comment by hectorsector** [comment]
👋 @hollenberry @beardofedu were you able to check this out?

**Comment by mukaxandy007** [comment]
Mui bien

**Comment by hollenberry** [comment]
@hectorsector We didn't get a chance during that call. Looks like this issue is still unresolved.
