### ISSUE TITLE
I need help with packages

### ISSUE THREAD

**Issue by westceno** [githubschool/on-demand-electron-app#3]
So I package my electron app, however when I go to start my app I get a javascript error. I can launch it from the command prompt but just not from the folder itself. @githubteacher

**Comment by beardofedu** [comment]
@westceno can you provide a screenshot of the error you are receiving?

**Comment by hollenberry** [comment]
@westceno closing this issue out for now to keep the repo tidy, but please feel free to re-open if you have a chance to follow up on @beardofedu 's comment to provide that screenshot.
