### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by conjones93** [githubschool/on-demand-electron-app#7]
I am trying to (a) create a repository and (b) push readme.md files into the repository.
I am having trouble pushing the files, can you help please?

**Comment by hollenberry** [comment]
Hey @conjones93 ! So sorry this ping flew under the radar. 

Are you working locally? If so, are you using your Command Line? 

We have a few resources for you to get started (https://services.github.com/on-demand/github-cli/), but if this doesn't work out please let me know where you're stuck and I can give better support.
